### ISSUE TITLE
DRC未通过

### ISSUE THREAD

**Issue by skcks** [jmz52/Hardware#3]
未连接项目有13个，请问作者还会继续完成吗

**Comment by jmz52** [comment]
This is a shields for STM32F407 dev board.
All 'disconnected' wires on the shield are connected via main board.

**Comment by skcks** [comment]
thanks,   understand now .  I already make some modification for it， I will test it later in this week.

![image](https://user-images.githubusercontent.com/2995881/59097723-dc6c8800-8950-11e9-9d11-baeae1370bbe.png)

![image](https://user-images.githubusercontent.com/2995881/59097640-a5967200-8950-11e9-81b9-6bb56faa5008.png)

![image](https://user-images.githubusercontent.com/2995881/59097664-b941d880-8950-11e9-909e-e37d58d15a13.png)
