### ISSUE TITLE
help config marlin suport tft_spi ili9341 2.8 touch

### ISSUE THREAD

**Issue by minhngoc123** [jmz52/Hardware#4]
![1](https://user-images.githubusercontent.com/70738064/93432229-6bf03d00-f8ef-11ea-9e66-0bc34e1bd4a5.PNG)
![Capture](https://user-images.githubusercontent.com/70738064/93432237-6dba0080-f8ef-11ea-8cc4-57f1aa5ca1bb.PNG)

hello,i want build marlin with stm32f407vet6 but i can't buid it .because when i build with vscode it show issues
no have spi tft config,only show
//=============================================================================
//=============================== Graphical TFTs ==============================
//=============================================================================

//
// FSMC display (MKS Robin, Alfawise U20, JGAurora A5S, REXYZ A1, etc.)
//
#define FSMC_GRAPHICAL_TFT

but build not complete 
link marlin i dowload: https://github.com/jmz52/Marlin
you can send me link marlin support tft_spi for stmf407vet6 ,thank you so much

**Comment by jmz52** [comment]
You need to use official repository - https://github.com/MarlinFirmware/Marlin
Enable `#define TFT_320x240_SPI` parameter in Configuration.h to use ili9341 SPI screen
Enable `#define TOUCH_SCREEN` parameter if you screen has touch panel

**Comment by minhngoc123** [comment]
![Capture](https://user-images.githubusercontent.com/70738064/93493950-a8935700-f936-11ea-9308-4dff66f368c1.PNG)
i dowload marlin : https://github.com/MarlinFirmware/Marlin
i configed :
#define MOTHERBOARD BOARD_BLACK_STM32F407VE  
#define SERIAL_PORT 1
#define TFT_320x240_SPI
#define TFT_DRIVER AUTO
#define TOUCH_SCREEN
#if ENABLED(TOUCH_SCREEN)
  #define BUTTON_DELAY_EDIT  50 // (ms) Button repeat delay for edit screens
  #define BUTTON_DELAY_MENU 250 // (ms) Button repeat delay for menus

  #define TOUCH_SCREEN_CALIBRATION

  #define XPT2046_X_CALIBRATION 12316
  #define XPT2046_Y_CALIBRATION -8981
  #define XPT2046_X_OFFSET        -43
  #define XPT2046_Y_OFFSET        257
#endif
into file platformio.ini
[platformio]
src_dir      = Marlin
boards_dir   = buildroot/share/PlatformIO/boards
default_envs = STM32F407VE_black
include_dir  = Marlin
but i build not complete 
![1](https://user-images.githubusercontent.com/70738064/93493040-aed50380-f935-11ea-9b60-89c706ca403f.PNG)
tft_spi support stm32f407vet6 ? thank you

**Comment by jmz52** [comment]
Missing pins are defining how you TFT and touch are connected.
Define them in pins file according to your schematic.

**Comment by minhngoc123** [comment]
i use code from file robin nano and add to file black_stm32f407ve 
code
![image](https://user-images.githubusercontent.com/70738064/93494850-b1d0f380-f937-11ea-9023-7942460683fa.png)
#if HAS_SPI_TFT

  // Shared SPI TFT

  #define LCD_BACKLIGHT_PIN                 PD13

  #define TOUCH_CS_PIN                      PE14  // SPI1_NSS
  #define TOUCH_SCK_PIN                     PA5   // SPI1_SCK
  #define TOUCH_MISO_PIN                    PA6   // SPI1_MISO
  #define TOUCH_MOSI_PIN                    PA7   // SPI1_MOSI

  #define BTN_EN1                           PE8
  #define BTN_EN2                           PE11
  #define BTN_ENC                           PE13

  #define TFT_CS_PIN                        PD11
  #define TFT_SCK_PIN                       PA5
  #define TFT_MISO_PIN                      PA6
  #define TFT_MOSI_PIN                      PA7
  #define TFT_DC_PIN                        PD10
  #define TFT_RST_PIN                       PC6
  #define TFT_A0_PIN                  TFT_DC_PIN

  #define TFT_RESET_PIN                     PC6
  #define TFT_BACKLIGHT_PIN                 PD13

  #define TOUCH_BUTTONS_HW_SPI
  #define TOUCH_BUTTONS_HW_SPI_DEVICE          1

  #ifndef TFT_WIDTH
    #define TFT_WIDTH                        480
  #endif
  #ifndef TFT_HEIGHT
    #define TFT_HEIGHT                       320
  #endif

  #define LCD_READ_ID                       0xD3
  #define LCD_USE_DMA_SPI

#endif
sorry my english verry bad .thank you

**Comment by minhngoc123** [comment]
can you send me file marlin was config for stm32f407vet6,thanks you
i dont understand code .when i add code it not work @@
gmail: xiunhanbin96@gmail.com
thank you so much
![Capture](https://user-images.githubusercontent.com/70738064/93495664-8f8ba580-f938-11ea-9572-3db4f37af88a.PNG)

**Comment by minhngoc123** [comment]
please help me,thank you so much

**Comment by jmz52** [comment]
@minhngoc123
It turns out that TFT SPI support is implemented for STM32F1xx only.
I've added some STM32F4xx specific code to address compilation errors, but I have no hardware to test it -  the STM32F407VE board installed in my printer is currently very busy and can't be removed.
I need to solder new shield for STM32F407VE board before I can test new code.

**Comment by minhngoc123** [comment]
oh,i hope it come soon for stm32f407vet6
and stm32f1xx , that stm32f103rbt6 suport, 
i have board : https://vi.aliexpress.com/item/32849464928.html
it support ?
i don't see config pin for stmf103rbt6 or stmf103rct6 . I only see CONFIG PIN FOR board robin nano ( stm32f103vet6)
thank you so much

**Comment by minhngoc123** [comment]
a config board robin nano v2
i change code into file platfom.ini 
i choose chip stm32f103rct6 and build
It seems that it suffers from insufficient memory
but stm32f103vet6 build ok
![Capture](https://user-images.githubusercontent.com/70738064/93691980-42195f00-fb17-11ea-9b57-1ff9058ac05a.PNG)

**Comment by minhngoc123** [comment]
i hope tft_spi for stmf103rct6 and stm32f407vet6 
i hope frome you

**Comment by jmz52** [comment]
I've uploaded updated code with support for SPI TFT on STM32F4.
It works just fine on my black STM32F407VE with ST77796 screen.

Technically it is possible to compile Marlin for EZT3D board.
There are two problems with this board
- board's native screen 128x128 TFT on ST7735 driver is not supported in Marlin yet
- MCU only has 128KB flash and this board is used in EZT-T1 delta printers. There is not enough flash to fit all features needed for delta printer.

**Comment by minhngoc123** [comment]
> I've uploaded updated code with support for Updated code with SPI TFT support for SPI TFT on STM32F4.
> It works just fine on my black STM32F407VE with ST77796 screen.
> 
> Technically it is possible to compile Marlin for EZT3D board.
> There are two problems with this board
> 
> * board's native screen 128x128 TFT on ST7735 driver is not supported in Marlin yet
> * MCU only has 128KB flash and this board is used in EZT-T1 delta printers. There is not enough flash to fit all features needed for delta printer.

**Comment by minhngoc123** [comment]
i try dowload marlin on github.com/jmz52/marlin but i dont see tft_spi
and  i try dowload marlin https://github.com/MarlinFirmware/Marlin
and i config board stm32f407_black but into file pin_stm32f407vet6_black no have config tft
and i coppycode mks robin nano v2 add it issue
![image](https://user-images.githubusercontent.com/70738064/93949931-2fe42e80-fd6c-11ea-8227-b56ffb329757.png)
i try define com port 1 and 2 
I USING DELTA PRINTER
can you  upload file config and file pin for stm32f407 use for hardware : https://github.com/jmz52/Hardware

                                                                     THANK YOU SO MUCH !
and code file black_stm32f407ve.h
/**
 * Marlin 3D Printer Firmware
 * Copyright (c) 2020 MarlinFirmware [https://github.com/MarlinFirmware/Marlin]
 *
 * Based on Sprinter and grbl.
 * Copyright (c) 2011 Camiel Gubbels / Erik van der Zalm
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 */
#pragma once

/**
 * STM32F407VET6 with RAMPS-like shield
 * 'Black' STM32F407VET6 board - https://www.stm32duino.com/viewtopic.php?t=485
 * Shield - https://github.com/jmz52/Hardware
 */

#if !defined(STM32F4) && !defined(STM32F4xx)
  #error "Oops! Select an STM32F4 board in 'Tools > Board.'"
#elif HOTENDS > 2 || E_STEPPERS > 2
  #error "Black STM32F4VET6 supports up to 2 hotends / E-steppers."
#endif

#ifndef BOARD_INFO_NAME
  #define BOARD_INFO_NAME "Black STM32F4VET6"
#endif

#define DEFAULT_MACHINE_NAME "STM32F407VET6"

//#define I2C_EEPROM
#define DISABLE_DEBUG

//
// EEPROM
//
//#define FLASH_EEPROM_EMULATION
//#define SDCARD_EEPROM_EMULATION

#if EITHER(NO_EEPROM_SELECTED, I2C_EEPROM)
  #define I2C_EEPROM                              // EEPROM on I2C-0
  #define MARLIN_EEPROM_SIZE              0x1000  // 4KB
#endif

//
// Note: MKS Robin board is using SPI2 interface.
//
//#define SPI_MODULE                           2
#define ENABLE_SPI2

//
// Limit Switches
//
#define X_DIAG_PIN                          PA15
#define Y_DIAG_PIN                          PA12
#define Z_DIAG_PIN                          PA11
#define E0_DIAG_PIN                         PC4
#define E1_DIAG_PIN                         PE7

#define X_STOP_PIN                          PA15
#define Y_STOP_PIN                          PA12
#define Z_MIN_PIN                           PA11
#define Z_MAX_PIN                           PC4

//
// Steppers
//
#define X_ENABLE_PIN                        PE4
#define X_STEP_PIN                          PE3
#define X_DIR_PIN                           PE2
#ifndef X_CS_PIN
  #define X_CS_PIN                          PD5
#endif

#define Y_ENABLE_PIN                        PE1
#define Y_STEP_PIN                          PE0
#define Y_DIR_PIN                           PB9
#ifndef Y_CS_PIN
  #define Y_CS_PIN                          PD7
#endif

#define Z_ENABLE_PIN                        PB8
#define Z_STEP_PIN                          PB5
#define Z_DIR_PIN                           PB4
#ifndef Z_CS_PIN
  #define Z_CS_PIN                          PD4
#endif

#define E0_ENABLE_PIN                       PB3
#define E0_STEP_PIN                         PD6
#define E0_DIR_PIN                          PD3
#ifndef E0_CS_PIN
  #define E0_CS_PIN                         PD9
#endif

#define E1_ENABLE_PIN                       PA3
#define E1_STEP_PIN                         PD15
#define E1_DIR_PIN                          PA1
#ifndef E1_CS_PIN
  #define E1_CS_PIN                         PD8
#endif

//
// Software SPI pins for TMC2130 stepper drivers
//
#if ENABLED(TMC_USE_SW_SPI)
  #ifndef TMC_SW_MOSI
    #define TMC_SW_MOSI                     PD14
  #endif
  #ifndef TMC_SW_MISO
    #define TMC_SW_MISO                     PD1
  #endif
  #ifndef TMC_SW_SCK
    #define TMC_SW_SCK                      PD0
  #endif
#endif

#if HAS_TMC_UART
  /**
   * TMC2208/TMC2209 stepper drivers
   *
   * Hardware serial communication ports.
   * If undefined software serial is used according to the pins below
   */
  //#define X_HARDWARE_SERIAL  Serial
  //#define X2_HARDWARE_SERIAL Serial1
  //#define Y_HARDWARE_SERIAL  Serial1
  //#define Y2_HARDWARE_SERIAL Serial1
  //#define Z_HARDWARE_SERIAL  Serial1
  //#define Z2_HARDWARE_SERIAL Serial1
  //#define E0_HARDWARE_SERIAL Serial1
  //#define E1_HARDWARE_SERIAL Serial1
  //#define E2_HARDWARE_SERIAL Serial1
  //#define E3_HARDWARE_SERIAL Serial1
  //#define E4_HARDWARE_SERIAL Serial1

  //
  // Software serial
  //

  #define X_SERIAL_TX_PIN                   PD5
  #define X_SERIAL_RX_PIN                   PD5

  #define Y_SERIAL_TX_PIN                   PD7
  #define Y_SERIAL_RX_PIN                   PD7

  #define Z_SERIAL_TX_PIN                   PD4
  #define Z_SERIAL_RX_PIN                   PD4

  #define E0_SERIAL_TX_PIN                  PD9
  #define E0_SERIAL_RX_PIN                  PD9

  #define E1_SERIAL_TX_PIN                  PD8
  #define E1_SERIAL_RX_PIN                  PD8

  // Reduce baud rate to improve software serial reliability
  #define TMC_BAUD_RATE                    19200
#endif // TMC2208 || TMC2209

//
// Temperature Sensors
//
#define TEMP_0_PIN                          PC1   // TH1
#define TEMP_1_PIN                          PC2   // TH2
#define TEMP_BED_PIN                        PC0   // TB1

//
// Heaters / Fans
//
#define HEATER_0_PIN                        PC3   // HEATER1
#define HEATER_1_PIN                        PB0   // HEATER2
#define HEATER_BED_PIN                      PA0   // HOT BED

#define FAN_PIN                             PB1   // FAN

//
// Thermocouples
//
//#define MAX6675_SS_PIN                    PE5   // TC1 - CS1
//#define MAX6675_SS_PIN                    PE6   // TC2 - CS2

//
// Misc. Functions
//
#define POWER_LOSS_PIN                      PA2   // PW_DET
#define PS_ON_PIN                           PA3   // PW_OFF

//#define SUICIDE_PIN                       PB2   // Enable MKSPWC support ROBIN NANO v1.2 ONLY
//#define SUICIDE_PIN_INVERTING            false

//#define KILL_PIN                          PA2   // Enable MKSPWC support ROBIN NANO v1.2 ONLY
//#define KILL_PIN_INVERTING                true  // Enable MKSPWC support ROBIN NANO v1.2 ONLY

#define SERVO0_PIN                          PA8   // Enable BLTOUCH support ROBIN NANO v1.2 ONLY

//#define LED_PIN                           PB2

#define MT_DET_1_PIN                        PA4
#define MT_DET_2_PIN                        PE6
#define MT_DET_PIN_INVERTING               false

#ifndef FIL_RUNOUT_PIN
  #define FIL_RUNOUT_PIN            MT_DET_1_PIN
#endif
#ifndef FIL_RUNOUT2_PIN
  #define FIL_RUNOUT2_PIN           MT_DET_2_PIN
#endif

#define WIFI_IO0_PIN                        PC13

//
// SD Card
//
#ifndef SDCARD_CONNECTION
  #define SDCARD_CONNECTION              ONBOARD
#endif

#define SDIO_SUPPORT
#define SDIO_CLOCK                       4500000  // 4.5 MHz
#define SD_DETECT_PIN                       PD12
#define ONBOARD_SD_CS_PIN                   PC11

//
// LCD / Controller
//
#ifndef BEEPER_PIN
  #define BEEPER_PIN                        PC5
#endif

/**
 * Note: MKS Robin TFT screens use various TFT controllers.
 * If the screen stays white, disable 'LCD_RESET_PIN'
 * to let the bootloader init the screen.
 */

#if HAS_SPI_TFT

  // Shared SPI TFT

  #define LCD_BACKLIGHT_PIN                 PD13

  #define TOUCH_CS_PIN                      PE14  // SPI1_NSS
  #define TOUCH_SCK_PIN                     PA5   // SPI1_SCK
  #define TOUCH_MISO_PIN                    PA6   // SPI1_MISO
  #define TOUCH_MOSI_PIN                    PA7   // SPI1_MOSI

  #define BTN_EN1                           PE8
  #define BTN_EN2                           PE11
  #define BTN_ENC                           PE13

  #define TFT_CS_PIN                        PD11
  #define TFT_SCK_PIN                       PA5
  #define TFT_MISO_PIN                      PA6
  #define TFT_MOSI_PIN                      PA7
  #define TFT_DC_PIN                        PD10
  #define TFT_RST_PIN                       PC6
  #define TFT_A0_PIN                  TFT_DC_PIN

  #define TFT_RESET_PIN                     PC6
  #define TFT_BACKLIGHT_PIN                 PD13

  #define TOUCH_BUTTONS_HW_SPI
  #define TOUCH_BUTTONS_HW_SPI_DEVICE          1

  #ifndef TFT_WIDTH
    #define TFT_WIDTH                        480
  #endif
  #ifndef TFT_HEIGHT
    #define TFT_HEIGHT                       320
  #endif

  #define LCD_READ_ID                       0xD3
  #define LCD_USE_DMA_SPI

#endif

#if ENABLED(TFT_LVGL_UI_SPI)

  // LVGL

  #define XPT2046_X_CALIBRATION           -17253
  #define XPT2046_Y_CALIBRATION            11579
  #define XPT2046_X_OFFSET                   514
  #define XPT2046_Y_OFFSET                   -24

#elif ENABLED(SPI_GRAPHICAL_TFT)

  // Emulated DOGM SPI

  #ifndef XPT2046_X_CALIBRATION
    #define XPT2046_X_CALIBRATION         -11386
  #endif
  #ifndef XPT2046_Y_CALIBRATION
    #define XPT2046_Y_CALIBRATION           8684
  #endif
  #ifndef XPT2046_X_OFFSET
    #define XPT2046_X_OFFSET                 339
  #endif
  #ifndef XPT2046_Y_OFFSET
    #define XPT2046_Y_OFFSET                 -18
  #endif

  #ifndef GRAPHICAL_TFT_UPSCALE
    #define GRAPHICAL_TFT_UPSCALE              3
  #endif
  #ifndef TFT_PIXEL_OFFSET_Y
    #define TFT_PIXEL_OFFSET_Y                32
  #endif

  #define BTN_ENC                           PE13
  #define BTN_EN1                           PE8
  #define BTN_EN2                           PE11

  #define LCD_PINS_ENABLE                   PD13
  #define LCD_PINS_RS                       PC6

#elif ENABLED(TFT_480x320_SPI)
    #define XPT2046_X_CALIBRATION         -17253
    #define XPT2046_Y_CALIBRATION          11579
    #define XPT2046_X_OFFSET                 514
    #define XPT2046_Y_OFFSET                 -24

    #define TFT_DRIVER                    ST7796
    #define TFT_BUFFER_SIZE                14400

#endif

#if HAS_SPI_LCD && !HAS_SPI_TFT

  // NON TFT Displays

  #if ENABLED(MKS_MINI_12864)

    // MKS MINI12864 and MKS LCD12864B
    // If using MKS LCD12864A (Need to remove RPK2 resistor)

    #define LCD_BACKLIGHT_PIN               -1
    #define LCD_RESET_PIN                   -1
    #define DOGLCD_A0                       PD11
    #define DOGLCD_CS                       PE15
    #define DOGLCD_SCK                      PA5
    #define DOGLCD_MOSI                     PA7

    // Required for MKS_MINI_12864 with this board
    #define MKS_LCD12864B
    #undef SHOW_BOOTSCREEN

  #else                                           // !MKS_MINI_12864

    #define LCD_PINS_D4                     PE14
    #if ENABLED(ULTIPANEL)
      #define LCD_PINS_D5                   PE15
      #define LCD_PINS_D6                   PD11
      #define LCD_PINS_D7                   PD10
    #endif

    #ifndef BOARD_ST7920_DELAY_1
      #define BOARD_ST7920_DELAY_1 DELAY_NS(125)
    #endif
    #ifndef BOARD_ST7920_DELAY_2
      #define BOARD_ST7920_DELAY_2 DELAY_NS(125)
    #endif
    #ifndef BOARD_ST7920_DELAY_3
      #define BOARD_ST7920_DELAY_3 DELAY_NS(125)
    #endif

  #endif // !MKS_MINI_12864

#endif // HAS_SPI_LCD && !HAS_SPI_TFT

#define HAS_SPI_FLASH                          1
#define SPI_FLASH_SIZE                 0x1000000  // 16MB
#if HAS_SPI_FLASH
  #define W25QXX_CS_PIN                     PB12
  #define W25QXX_MOSI_PIN                   PB15
  #define W25QXX_MISO_PIN                   PB14
  #define W25QXX_SCK_PIN                    PB13
#endif

//#if ENABLED(SPEAKER) && BEEPER_PIN == PC5
 //#error "MKS Robin nano default BEEPER_PIN is not a SPEAKER."
#endif

**Comment by jmz52** [comment]
Sorry, forgot to specify branch with updated code
https://github.com/jmz52/Marlin/tree/tft_and_touch_N2

**Comment by minhngoc123** [comment]
![a](https://user-images.githubusercontent.com/70738064/94091656-faf6db00-fe42-11ea-852b-a80a8221c698.PNG)
![b](https://user-images.githubusercontent.com/70738064/94091661-fcc09e80-fe42-11ea-890e-86343b46698e.PNG)
![c](https://user-images.githubusercontent.com/70738064/94091662-fd593500-fe42-11ea-8ba5-e0ba7afb96ea.PNG)
 THANK YOU SO MUCH
but i have issues main board have port com port 5,  but i can't connect to host .
file config  detault,i don't change it 

I'm sorry to bother you so much ,i can't fix it
THANK YOU SO MUCH
![120180036_1330694730608736_6982999155728254311_n](https://user-images.githubusercontent.com/70738064/94091971-d2bbac00-fe43-11ea-935e-2c7c8b3bc9a4.jpg)
![image](https://user-images.githubusercontent.com/70738064/94092107-144c5700-fe44-11ea-8ba3-32c76e96d195.png)

**Comment by jmz52** [comment]
It is a known issue with no USB reenumeration on MCU reset.
You need to power board from external power supply and connect USB cable once firmware is running.

**Comment by jmz52** [comment]
Black F407VE uses MCU's battery backed ram to emulate EEPROM. You need to install battery if you want to use this feature.

**Comment by minhngoc123** [comment]
thanks you so much,
and i have tft ili9341 2,8 with touch screen
how to calibration touch screen
i see in code :
#define TOUCH_SCREEN_CALIBRATION

  #define TOUCH_CALIBRATION_X   16692
  #define TOUCH_CALIBRATION_Y   11328
  #define TOUCH_OFFSET_X        -14
  #define TOUCH_OFFSET_Y        -20
  #define TOUCH_ORIENTATION     TOUCH_LANDSCAPE
I don't know where these figures are
and are you use facebook?
THANKS YOU SO MUCH

**Comment by jmz52** [comment]
Two ways to start built-in calibration:
- Connect to COM port at type M995 command.
- Press and hold (for 3 seconds if I recall correctly) non-interactive area on main screen.

Once calibration is completed , the calibration data will be displayed on COM port, so you can add them to your configuration file.
Alternatively you can save calibration data along with other settings to EEPROM using M50x commands

**Comment by minhngoc123** [comment]
thank you so much

**Comment by minhngoc123** [comment]
i try use external power supply and connect USB ,
the firt i use 5v power from samsung 2a changer ,led s2 flashes slow ,i connect usb com port but i can't connec to host,
in spite of device manager show usb serial com 5
i try use power 2s 7.4v and led flash off quickly,i connect usb 
https://drive.google.com/file/d/1NpUpZnS2FaP-yLThtrtLvi6a4QAAWR6k/view?usp=drivesdk
but ic power die and hot ,i seach schematic board i see board not have dioze protect usb power

**Comment by minhngoc123** [comment]
In the Future in the future, will stmf407 support ftf_lvgl_spi .thank you
