### ISSUE TITLE
Enstop to 5v or 3.3v

### ISSUE THREAD

**Issue by minhngoc123** [jmz52/Hardware#5]
![Capture+_2020-10-16-07-16-37](https://user-images.githubusercontent.com/70738064/96198660-a6490a80-0f7f-11eb-8ff5-6d5e9da1aea2.png)
I see schematic.i found out that the enstop is connected to 5v. will it damage stm32

**Comment by jmz52** [comment]
STM32 GPIOs are 5V tolerant.
5V is used for compatibility with active endstop.
Passive endstops usually connects signal pin with ground and do not use 5v line at all.

**Comment by minhngoc123** [comment]
Thank you so much
